### ISSUE TITLE
Group type of goals

### ISSUE THREAD

**Issue by VideoNMF** [Vin0uz/Futsal#27]
I suggest to group type of attacks in 6 groups :

- Strategy : Penalti, 10M, Touche, CPA and corner
- Attaque placée : 4-0 and Pivot
- Attaque rapide 
- Sortie de pression
- Powerplay : Gardien-Joueur & Défense Gardien-Joueur
- Transition : contre attaque, pression & récupération à la perte

However, it's necessary to have access at all datas in a new tab (for example : "Statistiques avancées")

**Comment by Vin0uz** [comment]
👏 That's a nice first issue ! 
To add some context, I would tell that behind this idea lays the fact that we have a lot of data presented currently in the charts (14 type of attacks if I remember well), and it makes it difficult to read. 

As an answer, we could have a `type_action` attribute, holding the main name (list of 6 that you proposed), and something like `details_action` that gives more precision (10M, 4-0, etc..).
Doing this would allow us to either display simple statistics for main charts, but still have access to details for a more advanced user view.

**Comment by VideoNMF** [comment]
Perfect 👍👌

**Comment by Vin0uz** [comment]
According to the data I have now, there is no "Attaque Rapide", but we do have "Autres" and "Touche" that you didn't classify in your list.
