### ISSUE TITLE
Bug data

### ISSUE THREAD

**Issue by VideoNMF** [Vin0uz/Futsal#47]

**Comment by VideoNMF** [comment]
Data of graph aren't exactly.

I don't know if it's normal so I put here ? 

It's mostly at the level of the days

**Comment by Vin0uz** [comment]
Yup sure here is a right place to say it :) 
If you can be bit more precise about which data is wrong and what should be displayed instead, it would be great 🙏

**Comment by VideoNMF** [comment]
![image](https://user-images.githubusercontent.com/53574079/82309922-05e8bd00-99c4-11ea-8afc-9cdbc0dd684c.png)
![image](https://user-images.githubusercontent.com/53574079/82309945-0bde9e00-99c4-11ea-8afb-3e1258217259.png)

The second graph is good but he missed journeys in the first graph.
Some are displayed and others are not (cf example NMF above)
However, the journeys who are displayed are good

**Comment by Vin0uz** [comment]
Ok I may have an idea why.. Maybe it is because of away/home games, I'll look at it, thanks for details !

**Comment by Vin0uz** [comment]
Soooo news on this. I spent some time, way too much I think, trying to fix the query doing this. In fact, it is most probably a conception issue, where home_team and away_team should be built differently. I will dig into that and keep updating on that issue :)

**Comment by VideoNMF** [comment]
It's perfect, the data are good but the journeys is not in the right direction
